CREATE TABLE BLOODGROUP (
    BLOOD_GROUP_ID INT PRIMARY KEY,
    TYPE VARCHAR2(5) NOT NULL
);


CREATE TABLE HOSPITAL (
    HOSPITAL_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    ADDRESS VARCHAR2(255)
);


CREATE TABLE LOCATIONN (
    LOCATION_ID INT PRIMARY KEY,
    CITY VARCHAR2(100),
    STATE VARCHAR2(100)
);


CREATE TABLE BLOODTEST (
    TEST_ID INT PRIMARY KEY,
    RESULT VARCHAR2(255),
    HEMOGLOBIN_LEVEL DECIMAL(5,2),
    DISEASE_DETECTED VARCHAR2(255)
);


CREATE TABLE DONOR (
    DONOR_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    AGE INT,
    GENDER CHAR(1),
    BLOOD_GROUP_ID INT,
    CONTACT_INFO VARCHAR2(100),
    FOREIGN KEY (BLOOD_GROUP_ID) REFERENCES BLOODGROUP(BLOOD_GROUP_ID)
);


CREATE TABLE RECIPIENT (
    RECIPIENT_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    AGE INT,
    GENDER CHAR(1),
    BLOOD_GROUP_ID INT,
    HOSPITAL_ID INT,
    FOREIGN KEY (BLOOD_GROUP_ID) REFERENCES BLOODGROUP(BLOOD_GROUP_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);


CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    ROLE VARCHAR2(50),
    HOSPITAL_ID INT,
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);


CREATE TABLE BLOODDONATION (
    DONATION_ID INT PRIMARY KEY,
    DONOR_ID INT,
    DATEIS DATE,
    TEST_ID INT,
    QUANTITY INT,
    STATUS VARCHAR2(20),
    FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID),
    FOREIGN KEY (TEST_ID) REFERENCES BLOODTEST(TEST_ID)
);


CREATE TABLE BLOODREQUEST (
    REQUEST_ID INT PRIMARY KEY,
    RECIPIENT_ID INT,
    ATDATE DATE,
    QUANTITY INT,
    STATUS VARCHAR2(20),
    FOREIGN KEY (RECIPIENT_ID) REFERENCES RECIPIENT(RECIPIENT_ID)
);


CREATE TABLE INVENTORY (
    INVENTORY_ID INT PRIMARY KEY,
    BLOOD_GROUP_ID INT,
    QUANTITY INT,
    EXPIRY_DATE DATE,
    LOCATION_ID INT,
    FOREIGN KEY (BLOOD_GROUP_ID) REFERENCES BLOODGROUP(BLOOD_GROUP_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONN(LOCATION_ID)
);


CREATE TABLE DONATIONCAMP (
    CAMP_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    CURRDATE DATE,
    LOCATION_ID INT,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONN(LOCATION_ID)
);


CREATE TABLE USERLOGIN (
    USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR2(50),
    PASSWORD_HASH VARCHAR2(255),
    ROLE VARCHAR2(50)
);


CREATE TABLE BLOODCOMPATIBILITY(
    RECIPIENT_BLOOD_GROUP_ID INT,
    DONOR_BLOOD_GROUP_ID INT,
    PRIMARY KEY (RECIPIENT_BLOOD_GROUP_ID, DONOR_BLOOD_GROUP_ID),
    FOREIGN KEY (RECIPIENT_BLOOD_GROUP_ID) REFERENCES BLOODGROUP(BLOOD_GROUP_ID),
    FOREIGN KEY (DONOR_BLOOD_GROUP_ID) REFERENCES BLOODGROUP(BLOOD_GROUP_ID)
);
