-- Donor Donation History

SELECT 
D.NAME,
BD.DATEIS,
BD.QUANTITY,
BD.STATUS
FROM DONOR D
JOIN BLOODDONATION BD
ON D.DONOR_ID = BD.DONOR_ID;



-- Recipient Hospital Details

SELECT
R.NAME AS RECIPIENT,
H.NAME AS HOSPITAL
FROM RECIPIENT R
JOIN HOSPITAL H
ON R.HOSPITAL_ID = H.HOSPITAL_ID;



-- Inventory Blood Group and Location

SELECT
BG.TYPE,
I.QUANTITY,
L.CITY,
L.STATE
FROM INVENTORY I
JOIN BLOODGROUP BG
ON I.BLOOD_GROUP_ID = BG.BLOOD_GROUP_ID
JOIN LOCATIONN L
ON I.LOCATION_ID = L.LOCATION_ID;



-- Blood Compatibility Rules

SELECT
R.TYPE AS RECIPIENT_GROUP,
D.TYPE AS DONOR_GROUP
FROM BLOODCOMPATIBILITY BC
JOIN BLOODGROUP R
ON BC.RECIPIENT_BLOOD_GROUP_ID = R.BLOOD_GROUP_ID
JOIN BLOODGROUP D
ON BC.DONOR_BLOOD_GROUP_ID = D.BLOOD_GROUP_ID;
